spring:  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lanyu123
    url: jdbc:mysql://106.54.126.205/SpringCloudSell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.137.121
    port: 6379
  rabbitmq:
    host: 192.168.137.121
    port: 5672
    username: guest
    password: guest  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  test
