server:
  port: 9091
  servlet:
    context-path: /lanyu
spring:
  datasource:
     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
     url: jdbc:sqlserver://localhost:1433;database=Lanyu
     username: lanyu
     password: lanyu123
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml       # mybatis配置文件位置
  mapper-locations: classpath:mybatis/mappers/*.xml           # mapper映射文件位置
  type-aliases-package: com.example.demo.entity  # 别名包
mapper:
  not-empty: true # insertSelective 和 updateByPrimaryKeySelective 中，是否判断字符串类型 !=''
  style: camelhumpAndLowercase # 实体和表转换时的默认规则:驼峰转下划线小写形式
  enableMethodAnnotation: true # 是否支持（getter 和 setter）在方法上使用注解，默认false
  enumAsSimpleType: true # 枚举类型当成基本类型对待

pagehelper:
  helper-dialect: sqlserver2012
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

# mybatis sql日志
logging:
  level:
    com:
      example:
        springbootmbg:
          mapper: trace