#所有环境的共用属性
management:
  endpoint:
    health:
      show-details: ${SOME_ENV}
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app-name: spring-boot-demo
  author: cuixu
#连字符
spring:
  profiles:
    active: dev
---
#profile=x的专用属性，也就是某个环境下的专用属性
#开发环境
spring:
  profiles: dev
---
#生产环境
spring:
  profiles: prod
server:
  tomcat:
    max-threads: 300
    max-connections: 10000
